# Site settings
name: John Ivan Diaz
title: John Ivan Diaz | Machine Learning Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://ivanintelligence.github.io/
baseurl: ''
email: diazjohnivantuyor@gmail.com
cover: https://ivanintelligence.github.io/img/og.png
logo: https://ivanintelligence.github.io/img/emojis/technologist.png
resume: https://ivanintelligence.github.io/JohnIvanDiaz_Resume.pdf
social:
  - title: linkedin
    url: https://www.linkedin.com/in/diazjohnivantuyor
  - title: github
    url: https://github.com/ivanintelligence
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: phone
    url: tel:+639927693173

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - 'vendor'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
