# Site settings
name: John Ivan Diaz
title: John Ivan Diaz
description: Artificial Intelligence / Machine Learning (AI/ML) Engineer
url: https://ivanintelligence.github.io
baseurl: ''

logo: /img/headshot/headshot-light.png
headshot-light: /img/headshot/headshot-light.png
headshot-dark: /img/headshot/headshot-dark.png
linkedin: https://www.linkedin.com/in/diazjohnivantuyor
email: mailto:diazjohnivantuyor@gmail.com
resume: /resume/JohnIvanDiaz_Resume.pdf

social:
  - title: resume
    url: /resume/JohnIvanDiaz_Resume.pdf
  - title: linkedin
    url: https://www.linkedin.com/in/diazjohnivantuyor
  - title: github
    url: https://github.com/ivanintelligence
  - title: email
    url: mailto:diazjohnivantuyor@gmail.com

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - 'vendor'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap