# Site settings
name: John Ivan Diaz
title: John Ivan Diaz | Machine Learning Engineer
description: A passionate Machine Learning Engineer who loves building intelligent systems
url: https://ivanintelligence.github.io/
baseurl: ''

logo: https://ivanintelligence.github.io/img/emojis/technologist.png
headshot: https://ivanintelligence.github.io/img/headshot.jpg

resume: https://ivanintelligence.github.io/JohnIvanDiaz_Resume.pdf
linkedin: https://www.linkedin.com/in/diazjohnivantuyor
email: diazjohnivantuyor@gmail.com

social:
  - title: resume
    url: https://ivanintelligence.github.io/JohnIvanDiaz_Resume.pdf
  - title: linkedin
    url: https://www.linkedin.com/in/diazjohnivantuyor
  - title: github
    url: https://github.com/ivanintelligence
  - title: email
    url: diazjohnivantuyor@gmail.com

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - 'vendor'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap